### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by msakrejda** [mrahtz/javascript-karplus-strong#1]
Is there a particular license for the code?

**Comment by mrahtz** [comment]
That's a good question :) I'll ask André and we'll see what we can work out.

**Comment by mrahtz** [comment]
I still haven't heard back from André, so I'm going to leave the project without a license, which from what I understand should mean that default copyright laws are in effect. I understand André's sources were developed further into [http://www.audiotool.com](Audiotool), so I don't want to step on his toes.
