### ISSUE TITLE
website 404

### ISSUE THREAD

**Issue by timqian** [mrahtz/javascript-karplus-strong#3]
Cool project! 

Find a small problem: The url on the introduction line need to be changed to http://amid.fish/javascript-karplus-strong to prevent 404

<img width="550" alt="screen shot 2016-09-13 at 10 00 21" src="https://cloud.githubusercontent.com/assets/5512552/18476661/87356a60-79fd-11e6-8cf2-a9a07086cf0c.png">

**Comment by mrahtz** [comment]
Oh, well spotted! 😅 Thank you for pointing that out!
